---
- hosts: YOURHOSTS
  become: yes
  become_user: root
  roles:
  - { role: mkl-install-role } 
  environment:
    http_proxy: "{{ lookup('env','http_proxy') }}"
    https_proxy: "{{ lookup('env','https_proxy') }}"
    HTTP_PROXY: "{{ lookup('env','HTTP_PROXY') }}"
    HTTPS_PROXY: "{{ lookup('env','HTTPS_PROXY') }}"
    no_proxy: "{{ lookup('env','no_proxy') }}"
    NO_PROXY: "{{ lookup('env','NO_PROXY') }}"